[workspace]
resolver="2"
members = ["program-derived-addresses"]

[workspace.dependencies]
# pinocchio
pinocchio = "0.9.2"
pinocchio-log = "0.4.0"
pinocchio-system = "0.4.0"
pinocchio-pubkey = "0.3.0"
bytemuck = { version = "1.23.0", features = ["derive"] }
