[package]
name = "checking-accounts"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio.workspace= true
pinocchio-log.workspace = true
pinocchio-system.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
