[package]
name = "hand"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = { version = "0.9.2" }
pinocchio-log.workspace = true
pinocchio-system.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
